name = "MatrixProfile"
uuid = "24e37439-14ec-4097-bda3-6a65822e2305"
authors = ["Fredrik Bagge Carlson"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
